version: 0.2

phases:
  install:
    commands:
      - npm install -g aws-cdk
      - python -m venv .venv
      - source .venv/bin/activate
      - pip install -r requirements.txt
  build:
    commands:
      - source .venv/bin/activate
      - cdk synth
      - cdk deploy --require-approval never

artifacts:
  files:
    - '**/*'
